spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: logs/${spring.application.name}.log