spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: logs/${spring.application.name}.log