spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  file:
    name: logs/${spring.application.name}.log