-- ----------------------------
-- Table structure for access_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."access_logs";
CREATE TABLE "public"."access_logs"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "url"                varchar(127),
    "http_method"        varchar(10),
    "params"             varchar(255),
    "body"               json,
    "ip"                 inet,
    "location"           varchar(64),
    "status_code"        int4,
    "response_times"     int8,
    "response_message"   varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(64),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(64),
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."access_logs"."id" IS '主键';
COMMENT
ON COLUMN "public"."access_logs"."url" IS '接口';
COMMENT
ON COLUMN "public"."access_logs"."http_method" IS 'http方法';
COMMENT
ON COLUMN "public"."access_logs"."params" IS '参数';
COMMENT
ON COLUMN "public"."access_logs"."body" IS '请求体';
COMMENT
ON COLUMN "public"."access_logs"."ip" IS 'IP地址';
COMMENT
ON COLUMN "public"."access_logs"."location" IS '位置';
COMMENT
ON COLUMN "public"."access_logs"."status_code" IS 'HTTP状态码';
COMMENT
ON COLUMN "public"."access_logs"."response_times" IS '响应时长';
COMMENT
ON COLUMN "public"."access_logs"."response_message" IS '响应消息';
COMMENT
ON COLUMN "public"."access_logs"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."access_logs"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."access_logs"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."access_logs"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."access_logs"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."access_logs" IS '访问日志表';

-- ----------------------------
-- Table structure for audit_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."audit_logs";
CREATE TABLE "public"."audit_logs"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "operation"          varchar(50)  NOT NULL,
    "resource"           varchar(50)  NOT NULL,
    "old_value"          text,
    "new_value"          text,
    "ip"                 varchar(50)  NOT NULL,
    "location"           varchar(100),
    "status_code"        int4         NOT NULL,
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(50),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(50),
    "last_modified_date" timestamp(6),
    "operated_times"     int8         NOT NULL
)
;
COMMENT
ON COLUMN "public"."audit_logs"."id" IS '主键，自增';
COMMENT
ON COLUMN "public"."audit_logs"."operation" IS '操作类型';
COMMENT
ON COLUMN "public"."audit_logs"."resource" IS '操作资源';
COMMENT
ON COLUMN "public"."audit_logs"."old_value" IS '旧值（JSON 格式）';
COMMENT
ON COLUMN "public"."audit_logs"."new_value" IS '新值（JSON 格式）';
COMMENT
ON COLUMN "public"."audit_logs"."ip" IS 'IP 地址';
COMMENT
ON COLUMN "public"."audit_logs"."location" IS '位置';
COMMENT
ON COLUMN "public"."audit_logs"."status_code" IS '状态码';
COMMENT
ON COLUMN "public"."audit_logs"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."audit_logs"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."audit_logs"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."audit_logs"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."audit_logs"."last_modified_date" IS '最后修改时间';
COMMENT
ON COLUMN "public"."audit_logs"."operated_times" IS '操作时长';
COMMENT
ON TABLE "public"."audit_logs" IS '审计日志表';

-- ----------------------------
-- Table structure for authorities
-- ----------------------------
DROP TABLE IF EXISTS "public"."authorities";
CREATE TABLE "public"."authorities"
(
    "id"        int8        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "username"  varchar(64) NOT NULL,
    "authority" varchar(64) NOT NULL
)
;
COMMENT
ON COLUMN "public"."authorities"."id" IS '主键';
COMMENT
ON COLUMN "public"."authorities"."username" IS '用户名';
COMMENT
ON COLUMN "public"."authorities"."authority" IS '权限';
COMMENT
ON TABLE "public"."authorities" IS '用户权限表';

-- ----------------------------
-- Table structure for dictionaries
-- ----------------------------
DROP TABLE IF EXISTS "public"."dictionaries";
CREATE TABLE "public"."dictionaries"
(
    "id"                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"               varchar(64)  NOT NULL,
    "superior_id"        int8,
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(64),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(64),
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."dictionaries"."id" IS '主键';
COMMENT
ON COLUMN "public"."dictionaries"."name" IS '名称';
COMMENT
ON COLUMN "public"."dictionaries"."superior_id" IS '上级ID';
COMMENT
ON COLUMN "public"."dictionaries"."description" IS '描述';
COMMENT
ON COLUMN "public"."dictionaries"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."dictionaries"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."dictionaries"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."dictionaries"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."dictionaries"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."dictionaries" IS '字典表';

-- ----------------------------
-- Table structure for file_records
-- ----------------------------
DROP TABLE IF EXISTS "public"."file_records";
CREATE TABLE "public"."file_records"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "name"               varchar(50)  NOT NULL,
    "type"               varchar(255),
    "path"               varchar(255),
    "size"               float4,
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(50),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(50),
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."file_records"."id" IS '主键';
COMMENT
ON COLUMN "public"."file_records"."name" IS '名称';
COMMENT
ON COLUMN "public"."file_records"."type" IS '类型';
COMMENT
ON COLUMN "public"."file_records"."path" IS '路径';
COMMENT
ON COLUMN "public"."file_records"."size" IS '大小';
COMMENT
ON COLUMN "public"."file_records"."description" IS '描述';
COMMENT
ON COLUMN "public"."file_records"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."file_records"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."file_records"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."file_records"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."file_records"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."file_records" IS '文件记录表';

-- ----------------------------
-- Table structure for group_authorities
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_authorities";
CREATE TABLE "public"."group_authorities"
(
    "id"        int8        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "group_id"  int8        NOT NULL,
    "authority" varchar(64) NOT NULL
)
;
COMMENT
ON COLUMN "public"."group_authorities"."id" IS '主键';
COMMENT
ON COLUMN "public"."group_authorities"."group_id" IS '用户组ID';
COMMENT
ON COLUMN "public"."group_authorities"."authority" IS '权限';
COMMENT
ON TABLE "public"."group_authorities" IS '用户组权限关系表';

-- ----------------------------
-- Table structure for group_members
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_members";
CREATE TABLE "public"."group_members"
(
    "id"       int8        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "group_id" int8        NOT NULL,
    "username" varchar(64) NOT NULL
)
;
COMMENT
ON COLUMN "public"."group_members"."id" IS '主键';
COMMENT
ON COLUMN "public"."group_members"."group_id" IS '用户组ID';
COMMENT
ON COLUMN "public"."group_members"."username" IS '用户名';
COMMENT
ON TABLE "public"."group_members" IS '用户组成员关系表';

-- ----------------------------
-- Table structure for group_privilege_actions
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_privilege_actions";
CREATE TABLE "public"."group_privilege_actions"
(
    "id"                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_privilege_id" int8         NOT NULL,
    "action"             varchar(127) NOT NULL
)
;
COMMENT
ON COLUMN "public"."group_privilege_actions"."id" IS '主键';
COMMENT
ON COLUMN "public"."group_privilege_actions"."group_privilege_id" IS '分组权限ID';
COMMENT
ON COLUMN "public"."group_privilege_actions"."action" IS '权限ID';
COMMENT
ON TABLE "public"."group_privilege_actions" IS '分组权限操作表';

-- ----------------------------
-- Table structure for group_privileges
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_privileges";
CREATE TABLE "public"."group_privileges"
(
    "id"           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_id"     int8 NOT NULL,
    "privilege_id" int8 NOT NULL
)
;
COMMENT
ON COLUMN "public"."group_privileges"."id" IS '主键';
COMMENT
ON COLUMN "public"."group_privileges"."group_id" IS '分组ID';
COMMENT
ON COLUMN "public"."group_privileges"."privilege_id" IS '权限ID';
COMMENT
ON TABLE "public"."group_privileges" IS '分组权限关系表';

-- ----------------------------
-- Table structure for group_roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_roles";
CREATE TABLE "public"."group_roles"
(
    "id"       int8 NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "group_id" int8 NOT NULL,
    "role_id"  int8 NOT NULL
)
;
COMMENT
ON COLUMN "public"."group_roles"."id" IS '主键';
COMMENT
ON COLUMN "public"."group_roles"."group_id" IS '用户组ID';
COMMENT
ON COLUMN "public"."group_roles"."role_id" IS '角色ID';
COMMENT
ON TABLE "public"."group_roles" IS '用户组角色关系表';

-- ----------------------------
-- Table structure for groups
-- ----------------------------
DROP TABLE IF EXISTS "public"."groups";
CREATE TABLE "public"."groups"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "group_name"         varchar(64)  NOT NULL,
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(64),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(64),
    "last_modified_date" timestamp(6),
    "superior_id"        int8
)
;
COMMENT
ON COLUMN "public"."groups"."id" IS '主键';
COMMENT
ON COLUMN "public"."groups"."group_name" IS '名称';
COMMENT
ON COLUMN "public"."groups"."description" IS '描述';
COMMENT
ON COLUMN "public"."groups"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."groups"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."groups"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."groups"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."groups"."last_modified_date" IS '最后修改时间';
COMMENT
ON COLUMN "public"."groups"."superior_id" IS '上级ID';
COMMENT
ON TABLE "public"."groups" IS '用户组表';

-- ----------------------------
-- Table structure for messages
-- ----------------------------
DROP TABLE IF EXISTS "public"."messages";
CREATE TABLE "public"."messages"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "title"              varchar(64)  NOT NULL,
    "body"            text,
    "unread"             bool         NOT NULL DEFAULT false,
    "receiver"           varchar(64)  NOT NULL,
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(64),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(64)  NOT NULL,
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."messages"."id" IS '主键';
COMMENT
ON COLUMN "public"."messages"."title" IS '标题';
COMMENT
ON COLUMN "public"."messages"."body" IS '内容';
COMMENT
ON COLUMN "public"."messages"."unread" IS '是否未读';
COMMENT
ON COLUMN "public"."messages"."receiver" IS '接收者';
COMMENT
ON COLUMN "public"."messages"."description" IS '描述';
COMMENT
ON COLUMN "public"."messages"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."messages"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."messages"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."messages"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."messages"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."messages" IS '消息表';

-- ----------------------------
-- Table structure for operation_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."operation_logs";
CREATE TABLE "public"."operation_logs"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "operation"          varchar(255),
    "os"                 varchar(50),
    "browser"            varchar(50),
    "ip"                 inet,
    "location"           varchar(50),
    "body"            varchar(1000),
    "user_agent"         varchar(255),
    "status_code"        int4,
    "response_message"   varchar(255),
    "referer"            varchar(255),
    "session_id"         varchar(50),
    "device_type"        varchar(20),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(50),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(50),
    "last_modified_date" timestamp(6),
    "operated_times"     int8
)
;
COMMENT
ON COLUMN "public"."operation_logs"."id" IS '主键';
COMMENT
ON COLUMN "public"."operation_logs"."operation" IS '操作';
COMMENT
ON COLUMN "public"."operation_logs"."os" IS '操作系统';
COMMENT
ON COLUMN "public"."operation_logs"."browser" IS '浏览器';
COMMENT
ON COLUMN "public"."operation_logs"."ip" IS 'IP地址';
COMMENT
ON COLUMN "public"."operation_logs"."location" IS '位置';
COMMENT
ON COLUMN "public"."operation_logs"."body" IS '内容';
COMMENT
ON COLUMN "public"."operation_logs"."user_agent" IS '用户代理信息';
COMMENT
ON COLUMN "public"."operation_logs"."status_code" IS 'HTTP状态码';
COMMENT
ON COLUMN "public"."operation_logs"."response_message" IS '响应消息';
COMMENT
ON COLUMN "public"."operation_logs"."referer" IS '来源页面';
COMMENT
ON COLUMN "public"."operation_logs"."session_id" IS '会话标识符';
COMMENT
ON COLUMN "public"."operation_logs"."device_type" IS '设备类型';
COMMENT
ON COLUMN "public"."operation_logs"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."operation_logs"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."operation_logs"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."operation_logs"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."operation_logs"."last_modified_date" IS '最后修改时间';
COMMENT
ON COLUMN "public"."operation_logs"."operated_times" IS '操作时长';
COMMENT
ON TABLE "public"."operation_logs" IS '访问日志表';

-- ----------------------------
-- Table structure for privilege_actions
-- ----------------------------
DROP TABLE IF EXISTS "public"."privilege_actions";
CREATE TABLE "public"."privilege_actions"
(
    "id"           int8        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "privilege_id" int8        NOT NULL,
    "action"       varchar(50) NOT NULL
)
;
COMMENT
ON COLUMN "public"."privilege_actions"."id" IS '主键';
COMMENT
ON COLUMN "public"."privilege_actions"."privilege_id" IS '权限ID';
COMMENT
ON COLUMN "public"."privilege_actions"."action" IS '操作';
COMMENT
ON TABLE "public"."privilege_actions" IS '权限操作表';

-- ----------------------------
-- Table structure for privileges
-- ----------------------------
DROP TABLE IF EXISTS "public"."privileges";
CREATE TABLE "public"."privileges"
(
    "id"                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "superior_id"        int8,
    "name"               varchar(64)  NOT NULL,
    "path"               varchar(127),
    "redirect"           varchar(255),
    "component"          varchar(255),
    "icon"               varchar(127),
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(64),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(64),
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."privileges"."id" IS '主键';
COMMENT
ON COLUMN "public"."privileges"."superior_id" IS '上级ID';
COMMENT
ON COLUMN "public"."privileges"."name" IS '名称';
COMMENT
ON COLUMN "public"."privileges"."path" IS '路径';
COMMENT
ON COLUMN "public"."privileges"."redirect" IS '跳转路径';
COMMENT
ON COLUMN "public"."privileges"."component" IS '组件路径';
COMMENT
ON COLUMN "public"."privileges"."icon" IS '图标';
COMMENT
ON COLUMN "public"."privileges"."description" IS '描述';
COMMENT
ON COLUMN "public"."privileges"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."privileges"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."privileges"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."privileges"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."privileges"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."privileges" IS '权限表';

-- ----------------------------
-- Table structure for role_members
-- ----------------------------
DROP TABLE IF EXISTS "public"."role_members";
CREATE TABLE "public"."role_members"
(
    "id"       int8        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "role_id"  int8        NOT NULL,
    "username" varchar(50) NOT NULL
)
;
COMMENT
ON COLUMN "public"."role_members"."id" IS '主键';
COMMENT
ON COLUMN "public"."role_members"."role_id" IS '角色ID';
COMMENT
ON COLUMN "public"."role_members"."username" IS '用户名';
COMMENT
ON TABLE "public"."role_members" IS '角色成员关系表';

-- ----------------------------
-- Table structure for role_privilege_actions
-- ----------------------------
DROP TABLE IF EXISTS "public"."role_privilege_actions";
CREATE TABLE "public"."role_privilege_actions"
(
    "id"                int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_privilege_id" int8         NOT NULL,
    "action"            varchar(127) NOT NULL
)
;
COMMENT
ON COLUMN "public"."role_privilege_actions"."id" IS '主键';
COMMENT
ON COLUMN "public"."role_privilege_actions"."role_privilege_id" IS '角色权限ID';
COMMENT
ON COLUMN "public"."role_privilege_actions"."action" IS '权限ID';
COMMENT
ON TABLE "public"."role_privilege_actions" IS '角色权限操作表';

-- ----------------------------
-- Table structure for role_privileges
-- ----------------------------
DROP TABLE IF EXISTS "public"."role_privileges";
CREATE TABLE "public"."role_privileges"
(
    "id"           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_id"      int8 NOT NULL,
    "privilege_id" int8 NOT NULL
)
;
COMMENT
ON COLUMN "public"."role_privileges"."id" IS '主键';
COMMENT
ON COLUMN "public"."role_privileges"."role_id" IS '角色ID';
COMMENT
ON COLUMN "public"."role_privileges"."privilege_id" IS '权限ID';
COMMENT
ON TABLE "public"."role_privileges" IS '角色权限关系表';

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."roles";
CREATE TABLE "public"."roles"
(
    "id"                 int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "name"               varchar(50)  NOT NULL,
    "description"        varchar(255),
    "enabled"            bool         NOT NULL DEFAULT true,
    "created_by"         varchar(50),
    "created_date"       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"   varchar(50),
    "last_modified_date" timestamp(6)
)
;
COMMENT
ON COLUMN "public"."roles"."id" IS '主键';
COMMENT
ON COLUMN "public"."roles"."name" IS '名称';
COMMENT
ON COLUMN "public"."roles"."description" IS '描述';
COMMENT
ON COLUMN "public"."roles"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."roles"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."roles"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."roles"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."roles"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."roles" IS '角色表';

-- ----------------------------
-- Table structure for user_privilege_actions
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_privilege_actions";
CREATE TABLE "public"."user_privilege_actions"
(
    "id"                int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_privilege_id" int8         NOT NULL,
    "action"            varchar(127) NOT NULL
)
;
COMMENT
ON COLUMN "public"."user_privilege_actions"."id" IS '主键';
COMMENT
ON COLUMN "public"."user_privilege_actions"."user_privilege_id" IS '用户权限ID';
COMMENT
ON COLUMN "public"."user_privilege_actions"."action" IS '权限ID';
COMMENT
ON TABLE "public"."user_privilege_actions" IS '用户权限操作表';

-- ----------------------------
-- Table structure for user_privileges
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_privileges";
CREATE TABLE "public"."user_privileges"
(
    "id"           int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"     varchar(64) NOT NULL,
    "privilege_id" int8        NOT NULL
)
;
COMMENT
ON COLUMN "public"."user_privileges"."id" IS '主键';
COMMENT
ON COLUMN "public"."user_privileges"."username" IS '账号';
COMMENT
ON COLUMN "public"."user_privileges"."privilege_id" IS '权限ID';
COMMENT
ON TABLE "public"."user_privileges" IS '用户权限关系表';

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users"
(
    "id"                     int8         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "username"               varchar(64)  NOT NULL,
    "password"               varchar(100) NOT NULL,
    "firstname"              varchar(64),
    "lastname"               varchar(64),
    "middle_name"            varchar(64),
    "email"                  varchar(64),
    "avatar"                 varchar(255),
    "enabled"                bool         NOT NULL DEFAULT true,
    "account_non_locked"     bool,
    "account_expires_at"     timestamp(6),
    "credentials_expires_at" timestamp(6),
    "created_by"             varchar(64),
    "created_date"           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified_by"       varchar(64),
    "last_modified_date"     timestamp(6)
)
;
COMMENT
ON COLUMN "public"."users"."id" IS '主键';
COMMENT
ON COLUMN "public"."users"."username" IS '用户名';
COMMENT
ON COLUMN "public"."users"."password" IS '密码';
COMMENT
ON COLUMN "public"."users"."firstname" IS '名字';
COMMENT
ON COLUMN "public"."users"."lastname" IS '姓';
COMMENT
ON COLUMN "public"."users"."middle_name" IS '中间名';
COMMENT
ON COLUMN "public"."users"."email" IS '邮箱';
COMMENT
ON COLUMN "public"."users"."avatar" IS '头像';
COMMENT
ON COLUMN "public"."users"."enabled" IS '是否启用';
COMMENT
ON COLUMN "public"."users"."account_non_locked" IS '是否未锁定';
COMMENT
ON COLUMN "public"."users"."account_expires_at" IS '失效时间';
COMMENT
ON COLUMN "public"."users"."credentials_expires_at" IS '密码失效时间';
COMMENT
ON COLUMN "public"."users"."created_by" IS '创建者';
COMMENT
ON COLUMN "public"."users"."created_date" IS '创建时间';
COMMENT
ON COLUMN "public"."users"."last_modified_by" IS '最后修改者';
COMMENT
ON COLUMN "public"."users"."last_modified_date" IS '最后修改时间';
COMMENT
ON TABLE "public"."users" IS '用户表';


-- ----------------------------
-- Indexes structure for table authorities
-- ----------------------------
CREATE UNIQUE INDEX "ix_auth_username" ON "public"."authorities" USING btree (
    "username" "pg_catalog"."text_ops" ASC NULLS LAST,
    "authority" "pg_catalog"."text_ops" ASC NULLS LAST
    );


-- ----------------------------
-- Uniques structure for table roles
-- ----------------------------
ALTER TABLE "public"."roles"
    ADD CONSTRAINT "uk_roles_name" UNIQUE ("name");


-- ----------------------------
-- Uniques structure for table users
-- ----------------------------
ALTER TABLE "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");


-- ----------------------------
-- Foreign Keys structure for table group_members
-- ----------------------------
ALTER TABLE "public"."group_members"
    ADD CONSTRAINT "fk_group_members_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."group_members"
    ADD CONSTRAINT "fk_group_members_username" FOREIGN KEY ("username") REFERENCES "public"."users" ("username") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table group_privilege_actions
-- ----------------------------
ALTER TABLE "public"."group_privilege_actions"
    ADD CONSTRAINT "fk_group_privilege_actions_id" FOREIGN KEY ("group_privilege_id") REFERENCES "public"."group_privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table group_privileges
-- ----------------------------
ALTER TABLE "public"."group_privileges"
    ADD CONSTRAINT "fk_group_privileges_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."group_privileges"
    ADD CONSTRAINT "fk_group_privileges_privilege_id" FOREIGN KEY ("privilege_id") REFERENCES "public"."privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table group_roles
-- ----------------------------
ALTER TABLE "public"."group_roles"
    ADD CONSTRAINT "fk_group_roles_groups" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."group_roles"
    ADD CONSTRAINT "fk_group_roles_roles" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table privilege_actions
-- ----------------------------
ALTER TABLE "public"."privilege_actions"
    ADD CONSTRAINT "fk_privileges_action" FOREIGN KEY ("privilege_id") REFERENCES "public"."privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table role_members
-- ----------------------------
ALTER TABLE "public"."role_members"
    ADD CONSTRAINT "fk_role_members_roles" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."role_members"
    ADD CONSTRAINT "fk_role_members_users" FOREIGN KEY ("username") REFERENCES "public"."users" ("username") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table role_privilege_actions
-- ----------------------------
ALTER TABLE "public"."role_privilege_actions"
    ADD CONSTRAINT "fk_role_privilege_actions_id" FOREIGN KEY ("role_privilege_id") REFERENCES "public"."role_privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table role_privileges
-- ----------------------------
ALTER TABLE "public"."role_privileges"
    ADD CONSTRAINT "fk_role_privileges_privilege_id" FOREIGN KEY ("privilege_id") REFERENCES "public"."privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."role_privileges"
    ADD CONSTRAINT "fk_role_privileges_role_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table user_privilege_actions
-- ----------------------------
ALTER TABLE "public"."user_privilege_actions"
    ADD CONSTRAINT "fk_user_privilege_actions_id" FOREIGN KEY ("user_privilege_id") REFERENCES "public"."user_privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table user_privileges
-- ----------------------------
ALTER TABLE "public"."user_privileges"
    ADD CONSTRAINT "fk_user_privileges_privilege_id" FOREIGN KEY ("privilege_id") REFERENCES "public"."privileges" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."user_privileges"
    ADD CONSTRAINT "fk_user_privileges_username" FOREIGN KEY ("username") REFERENCES "public"."users" ("username") ON DELETE NO ACTION ON UPDATE NO ACTION;
